name: Build and Deploy bo3-multiples-pricing

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli@latest

      - name: Install root dependencies
        run: npm install --ignore-scripts

      - name: Deploy to Shopify
        env:
          SHOPIFY_CLI_PARTNERS_TOKEN: ${{ secrets.SHOPIFY_CLI_PARTNERS_TOKEN }}
          SHOPIFY_FLAG_STORE: td5h8u-tb.myshopify.com
          SHOPIFY_CLI_TTY: "0"
          NO_COLOR: "1"
          CI: "true"
        run: shopify app deploy --force --no-color --client-id b6ef0586e8f3f9038f0397c65d866dbd
